Change of the ffmpeg to libav-tools
The following error was produced with ffmpeg when the docker image was built on a Raspberry Pi 3:

----
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ffmpeg' has no installation candidate
The command '/bin/sh -c /install/install_deb_packages.sh' returned a non-zero code: 100
ERROR: docker build failed. Dockerfile is at .....
----

Changing ffmpeg to libav-tools to this file (install_deb_packages.sh) allowed the installation to continue.